{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ghostmail
  labels:
    app: ghostmail
    release: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ default (printf "mail.%s" .Values.domain) .Values.hostname }}
      secretName: {{ default (printf "%s-ghostmail-tls" .Release.Name) .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ default (printf "mail.%s" .Values.domain) .Values.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-ghostmail
                port:
                  name: http
{{- end }}
