apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ghostmail-secret
  labels:
    app: ghostmail
    release: {{ .Release.Name }}
type: Opaque
data:
  admin-password: {{ default (randAlphaNum 24) .Values.admin.password | b64enc | quote }}
